In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('train.csv')

In [4]:
df.sample(100)

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
11031,11032,2469,346,19,85,12,1307,181,207,163,...,0,0,0,0,0,0,0,0,0,6
14182,14183,3180,334,11,90,13,1310,194,225,170,...,0,0,0,0,0,0,0,0,0,1
6833,6834,2716,205,26,67,25,1087,196,253,179,...,0,0,0,0,0,0,0,0,0,5
9315,9316,3344,351,19,552,10,3770,184,205,157,...,0,0,0,0,0,0,0,0,1,7
10600,10601,3200,187,11,30,-4,2240,221,248,159,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11098,11099,2601,18,15,300,0,1690,208,208,134,...,0,0,0,0,0,0,0,0,0,6
9909,9910,3042,1,10,268,126,2922,206,221,153,...,0,1,0,0,0,0,0,0,0,1
8320,8321,2971,111,25,391,226,1952,253,204,63,...,0,0,0,0,0,0,0,0,0,5
14534,14535,3682,0,14,1189,327,5228,199,213,151,...,0,0,0,0,0,0,0,0,1,7


In [ ]:
df.iloc[1].values

array([   2, 2590,   56,    2,  212,   -6,  390,  220,  235,  151, 6225,
          1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          5])

In [5]:
df.drop('Id', axis=1, inplace=True)

In [6]:
df.shape

(15120, 55)

In [7]:
df.duplicated().sum()

np.int64(0)

In [ ]:
from sklearn.decomposition import PCA
# pca = PCA(n_components=2) # Assuming you want 2 components, adjust as needed

In [ ]:
# X_train_pca = pca.fit_transform(X_train)
# X_test_pca = pca.transform(X_test)

# print("Shape of X_train after PCA:", X_train_pca.shape)
# print("Shape of X_test after PCA:", X_test_pca.shape)

In [ ]:
# import matplotlib.pyplot as plt
# import seaborn as sns

# plt.figure(figsize=(10, 8))
# sns.scatterplot(x=X_train_pca[:, 0], y=X_train_pca[:, 1], hue=y_train, palette='viridis', legend='full')
# plt.title('PCA of Training Data colored by Cover_Type')
# plt.xlabel('Principal Component 1')
# plt.ylabel('Principal Component 2')
# plt.legend(title='Cover_Type')
# plt.grid(True)
# plt.show()

In [ ]:
pca_3d = PCA(n_components=3)

X_train_pca_3d = pca_3d.fit_transform(X_train)
X_test_pca_3d = pca_3d.transform(X_test)

print("Shape of X_train after PCA:", X_train_pca_3d.shape)
print("Shape of X_test after PCA:", X_test_pca_3d.shape)

Shape of X_train after PCA: (11340, 3)
Shape of X_test after PCA: (3780, 3)


In [ ]:
# import matplotlib.pyplot as plt
# from mpl_toolkits.mplot3d import Axes3D

# fig = plt.figure(figsize=(10, 8))
# ax = fig.add_subplot(111, projection='3d')

# scatter = ax.scatter(X_train_pca_3d[:, 0],
#                      X_train_pca_3d[:, 1],
#                      X_train_pca_3d[:, 2],
#                      c=y_train.astype('category').cat.codes,  # color by class
#                      cmap='tab10')

# ax.set_xlabel('Principal Component 1')
# ax.set_ylabel('Principal Component 2')
# ax.set_zlabel('Principal Component 3')
# ax.set_title('3D Scatter Plot of PCA-transformed Training Data by Cover Type')

# plt.colorbar(scatter, label='Cover Type')
# plt.show()

In [ ]:
import plotly.express as px

# Create a DataFrame for Plotly
# It's good practice to put your PCA results into a DataFrame with the target variable
# for easier plotting with plotly.express.
pca_3d_df = pd.DataFrame({
    'PC1': X_train_pca_3d[:, 0],
    'PC2': X_train_pca_3d[:, 1],
    'PC3': X_train_pca_3d[:, 2],
    'Cover_Type': y_train.values
})

fig = px.scatter_3d(pca_3d_df,
                    x='PC1',
                    y='PC2',
                    z='PC3',
                    color='Cover_Type',
                    title='Interactive 3D PCA of Training Data by Cover Type',
                    labels={'PC1': 'Principal Component 1',
                            'PC2': 'Principal Component 2',
                            'PC3': 'Principal Component 3'},
                    height=700) # Adjust height for better visibility

fig.show()

In [8]:
X = df.drop('Cover_Type', axis=1)
y = df['Cover_Type']

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [10]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((11340, 54), (3780, 54), (11340,), (3780,))

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

In [13]:
from sklearn.metrics import accuracy_score
y_pred = rf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8621693121693121


In [ ]:
# import matplotlib.pyplot as plt
# import seaborn as sns
# from sklearn.ensemble import RandomForestClassifier

# # Retrain RandomForest on PCA 2D data
# # This model will be used to predict the decision boundaries in the 2D PCA space
# rf_pca_2d = RandomForestClassifier(random_state=42, n_estimators=100)
# rf_pca_2d.fit(X_train_pca, y_train)

In [ ]:
# # Create a meshgrid for visualizing the decision boundary in 2D
# # Determine the min/max for each principal component, adding a small buffer
# x_min_2d, x_max_2d = X_train_pca[:, 0].min() - 100, X_train_pca[:, 0].max() + 100
# y_min_2d, y_max_2d = X_train_pca[:, 1].min() - 100, X_train_pca[:, 1].max() + 100

# # Define step size for the meshgrid.
# # A smaller step size leads to higher resolution but also higher computation time.
# step_size_2d = 50 # This can be adjusted for more detail.

# xx_2d, yy_2d = np.meshgrid(np.arange(x_min_2d, x_max_2d, step_size_2d),
#                            np.arange(y_min_2d, y_max_2d, step_size_2d))

# # Predict on the meshgrid points using the retrained RandomForest model
# grid_points_2d = np.c_[xx_2d.ravel(), yy_2d.ravel()]
# Z_predicted_2d = rf_pca_2d.predict(grid_points_2d)

# # Reshape the predictions to match the meshgrid for plotting
# Z_predicted_2d = Z_predicted_2d.reshape(xx_2d.shape)

In [ ]:
# plt.figure(figsize=(12, 8))

# # Plot the decision boundaries
# plt.contourf(xx_2d, yy_2d, Z_predicted_2d, alpha=0.5, cmap='viridis')

# # Plot the actual data points
# sns.scatterplot(x=X_train_pca[:, 0], y=X_train_pca[:, 1], hue=y_train,
#                 palette='viridis', legend='full', s=20, alpha=0.8)

# plt.title('2D Decision Boundaries of RandomForest on PCA Components')
# plt.xlabel('Principal Component 1')
# plt.ylabel('Principal Component 2')
# plt.legend(title='Cover_Type')
# plt.grid(True)
# plt.show()

In [ ]:
# import pickle

# pickle.dump(rf, open('forest.pkl', 'wb'))

In [18]:
df.iloc[101].values

array([2684,   84,   12,  150,    2, 1677,  237,  220,  113, 5693,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    1,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    2])

In [19]:
input = [2684,   84,   12,  150,    2, 1677,  237,  220,  113, 5693,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    1,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0]

In [20]:
import numpy as np
pred = np.array(input).reshape(1, -1)
pred

array([[2684,   84,   12,  150,    2, 1677,  237,  220,  113, 5693,    1,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    1,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0]])

In [21]:
rf.predict(pred)

c:\Users\RISHAV\OneDrive\Desktop\Python\Projects\Project 12-Forest Cover Type Prediction\.forest_cover_type_emv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([2])

In [22]:
import sklearn
print(sklearn.__version__)


1.8.0


In [24]:
df.columns

Index(['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology',
       'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways',
       'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm',
       'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area1',
       'Wilderness_Area2', 'Wilderness_Area3', 'Wilderness_Area4',
       'Soil_Type1', 'Soil_Type2', 'Soil_Type3', 'Soil_Type4', 'Soil_Type5',
       'Soil_Type6', 'Soil_Type7', 'Soil_Type8', 'Soil_Type9', 'Soil_Type10',
       'Soil_Type11', 'Soil_Type12', 'Soil_Type13', 'Soil_Type14',
       'Soil_Type15', 'Soil_Type16', 'Soil_Type17', 'Soil_Type18',
       'Soil_Type19', 'Soil_Type20', 'Soil_Type21', 'Soil_Type22',
       'Soil_Type23', 'Soil_Type24', 'Soil_Type25', 'Soil_Type26',
       'Soil_Type27', 'Soil_Type28', 'Soil_Type29', 'Soil_Type30',
       'Soil_Type31', 'Soil_Type32', 'Soil_Type33', 'Soil_Type34',
       'Soil_Type35', 'Soil_Type36', 'Soil_Type37', 'Soil_Type38',
       'Soil_Type39', 'Soil_Type40